# YAML 1.1
# https://app.travis-ci.com/
# github@myvas.com
language: cpp

branches:
  only:
  - main

before_script:
  - eval "${MATRIX_EVAL}"
  - $CXX --version

script:
  - mkdir build && cd ./build
  - cmake ..
  - make
  - ctest

notifications:
  email: false

# ubuntu 22.04, git 2.36.1, git-lfs 3.0.2, cmake 3.16.8, gcc 11.2.0, clang 7.0.0, python 3.10
dist: jammy

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-11']
      env:
        - MATRIX_EVAL="CC=gcc-11 && CXX=g++-11"
