# YAML 1.1
# https://app.travis-ci.com/
# github@myvas.com
language: cpp

branches:
  only:
  - main
notifications:
  email: false

# ubuntu 22.04, bash 5.1.16, sudo 1.9.9
# git 2.40.1, git-lfs 3.0.2
# cmake 3.26.3, gcc 11.3.0/11.4.0, clang 16.0.0, python 3.10
dist: jammy
sudo: required
before_install:
  - sudo apt-get -y install doxygen
  - sudo apt-get -y install graphviz
before_script:
  - eval "${MATRIX_EVAL}"
  - $CXX --version
script:
  - mkdir build && cd ./build
  - cmake ..
  - make
  - ctest

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-11']
      env:
        - MATRIX_EVAL="CC=gcc-11 && CXX=g++-11"
