version: 0.2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
skip_non_tags: true
image: Ubuntu2004
configuration: Release
platform: x64
clone_depth: 3
install:
- sh: >-
    sudo apt-get install -y doxygen

    sudo apt-get install -y graphviz
build_script:
- sh: >-
    mkdir build && cd ./build

    cmake ..

    make package

    make package_source
test_script:
- sh: ctest
notifications:
- provider: Email
  to:
  - github@myvas.com
  subject: Report from ci.appveyor.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true